[changelog]
body = """
{% for group, commits in commits | group_by(attribute="group") %}
### {{ group | striptags | trim }}
{% for commit in commits -%}
- {% if commit.breaking %}[breaking] {% endif %}{{ commit.message | upper_first }}{% if commit.remote.username %} by [@{{ commit.remote.username }}](https://github.com/{{ commit.remote.username }}){% endif %}{% if commit.remote.pr_number %} in [#{{ commit.remote.pr_number }}](https://github.com/{{ remote.github.owner }}/{{ remote.github.repo }}/pull/{{ commit.remote.pr_number }}){% else %} · [`{{ commit.id | truncate(length=7, end="") }}`](https://github.com/{{ remote.github.owner }}/{{ remote.github.repo }}/commit/{{ commit.id }}){% endif %}
{% endfor %}

{% endfor %}
{% set new_contributors = github.contributors | filter(attribute="is_first_time", value=true) %}
{% if new_contributors | length > 0 %}
### New Contributors
{% for contributor in new_contributors -%}
- [@{{ contributor.username }}](https://github.com/{{ contributor.username }}) made their first contribution{% if contributor.pr_number %} in [#{{ contributor.pr_number }}](https://github.com/{{ remote.github.owner }}/{{ remote.github.repo }}/pull/{{ contributor.pr_number }}){% endif %}
{% endfor %}
{% endif %}
{% if previous and previous.version %}
**Full Changelog:** [`{{ previous.version }}...{{ version }}`](https://github.com/{{ remote.github.owner }}/{{ remote.github.repo }}/compare/{{ previous.version }}...{{ version }})
{% else %}
**Full Changelog:** Initial release
{% endif %}
"""

trim = true
render_always = true
postprocessors = [
  { pattern = "\n{3,}", replace = "\n\n" },
]

[git]
conventional_commits = true
filter_unconventional = false
protect_breaking_commits = true
tag_pattern = "v[0-9]+\\.[0-9]+\\.[0-9]+"
sort_commits = "oldest"

commit_parsers = [
  { message = "^feat", group = "<!-- 0 -->Features" },
  { message = "^fix", group = "<!-- 1 -->Bug Fixes" },
  { message = "^perf", group = "<!-- 2 -->Performance" },
  { message = "^refactor", group = "<!-- 3 -->Improvements" },
  { message = "^docs?", group = "<!-- 4 -->Documentation" },
  { message = "^style", group = "<!-- 5 -->Style" },
  { message = "^test", group = "<!-- 6 -->Testing" },
  { message = "^build", group = "<!-- 7 -->Build and CI" },
  { message = "^ci", group = "<!-- 7 -->Build and CI" },
  { message = "^Merge ", skip = true },
  { message = "^Update README\\.md$", skip = true },
  { message = "^Updated README\\.md$", skip = true },
  { message = "^chore: update changelog", skip = true },
  { message = "^chore: bump version", skip = true },
  { message = "^chore: update flake\\.nix", skip = true },
  { message = "^chore", group = "<!-- 8 -->Maintenance" },
  { body = ".*security", group = "<!-- 9 -->Security" },
  { message = "^revert", group = "<!-- 10 -->Reverts" },
  { message = ".*", group = "<!-- 11 -->Maintenance" },
]
