.TH CWAL 5 "August 2026" "cwal 0.9.0" "File Formats"
.ss 12 0
.ad l
.am SH
.ad l
..
.am PP
.ad l
..
.am TP
.ad l
..
.am B
.ad l
..
.am BI
.ad l
..
.am BR
.ad l
..
.am I
.ad l
..
.am IP
.ad l
..
.am IR
.ad l
..
.SH NAME
cwal.ini \- configuration file for cwal
.SH DESCRIPTION
.B cwal
follows the XDG Base Directory Specification.
The INI configuration file is located at
.I ${XDG_CONFIG_HOME:-~/.config}/cwal/cwal.ini
and is created automatically with default values on first run.
Comments start with
.B #
or
.BR ; .
.SH CONFIGURATION
.nf
[general]
out_dir = /home/user/.cache/cwal/
backend = cwal
script_path = /home/user/.local/bin/post-cwal.sh

[options]
alpha = 1.00
saturation = 0.00
contrast = 1.00
mode = dark
cols16_mode = darken
skip_cursor = false

[random]
random_dir = /home/user/Pictures/Wallpapers

[links]
# format: template_name = destination_path | reload_command
colors-waybar.css = ~/.config/waybar/colors.css | pkill -USR2 waybar
colors-kitty.conf = ~/.config/kitty/current-theme.conf
_ = | pkill -USR2 waybar
.fi
.TP
.BR \&[general] " \-\- " out_dir ", " backend ", " script_path
Defaults for the corresponding command-line options of
.BR cwal (1).
.TP
.BR \&[options] " \-\- " alpha ", " saturation ", " contrast ", " mode ", " cols16_mode ", " skip_cursor
Color generation and output options:
.TS
l l.
alpha	Alpha transparency (0.0-1.0)
saturation	Overall saturation
contrast	Contrast ratio
mode	dark or light
cols16_mode	darken, lighten, or none
skip_cursor	true or false
.TE
.TP
.BR \&[random] " \-\- " random_dir
Directory used by
.BR cwal " " \-\-random
when no directory is given.
.TP
.BR \&[links] " \-\- " template_name " = " destination_path " | " reload_command
Copies the rendered template output to
.I destination_path
and/or runs
.I reload_command
after processing.
Omit the destination to only run the reload command; use an arbitrary alias,
such as
.BR _ ,
as the template name in that case.
The template name itself need not match an installed template.
.SH FILES
.TP
.I ${XDG_CONFIG_HOME:-~/.config}/cwal/cwal.ini
Main configuration file.
Created with defaults on first run.
.TP
.I ${XDG_CACHE_HOME:-~/.cache}/cwal
Default output directory; holds generated files and caches.
.TP
.I ${XDG_CACHE_HOME:-~/.cache}/cwal/cwal
Record of the last processed image path, used by
.BR cwal " " \-\-restore .
.TP
.I ${XDG_CACHE_HOME:-~/.cache}/cwal/schemes/<image>_<mode>_<cols16>_s<float>_c<float>_a<float>_<backend>.cwal
Cached palettes, one per image, mode, and backend combination.
.TP
.I ${XDG_DATA_DIRS:-/usr/local/share:/usr/share}/cwal/templates
System-wide template directory.
.TP
.I ${XDG_DATA_HOME:-~/.local/share}/cwal/templates
User data template directory.
.TP
.I ${XDG_CONFIG_HOME:-~/.config}/cwal/templates
User config template directory.
.TP
.I ${XDG_DATA_DIRS:-/usr/local/share:/usr/share}/cwal/themes
System-wide theme directory.
.TP
.I ${XDG_CONFIG_HOME:-~/.config}/cwal/themes
User config theme directory.
.TP
.I ${XDG_CONFIG_HOME:-~/.config}/cwal/backends
Directory for Lua backend scripts (created if missing).
.SH SEE ALSO
.BR cwal (1),
.BR cwal (7)
.SH COPYRIGHT
Copyright (c) 2026 Nitin Bhat. Licensed under the GNU General Public License
v3.0.